# Generated by Django 3.2.10 on 2023-12-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=500)),
                ('nick_text', models.CharField(max_length=500)),
                ('department_text', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('building_number', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('photo', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
